# Generated by Django 3.2 on 2022-01-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20220119_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='detail',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
