# Generated by Django 3.2 on 2022-01-19 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0004_auto_20220119_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downvote',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='downvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='user',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_by',
        ),
        migrations.AddField(
            model_name='answer',
            name='body',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='detail',
            field=models.TextField(blank=True, default='', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Downvote',
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
