# Generated by Django 3.2 on 2022-01-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletters',
            options={'verbose_name_plural': 'newsletters'},
        ),
        migrations.RemoveField(
            model_name='newsletters',
            name='mewsletters_body',
        ),
        migrations.AddField(
            model_name='newsletters',
            name='newsletters_body',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='newsletters',
            name='newsletters_by',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='newsletters',
            name='newsletters_title',
            field=models.CharField(max_length=254),
        ),
    ]
