# Generated by Django 3.2 on 2022-01-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_auto_20220122_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletters',
            name='newsletters_title',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
