# Generated by Django 3.2 on 2022-01-23 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_rename_usder_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_name', models.CharField(blank=True, max_length=245, null=True)),
                ('review_body', models.TextField(blank=True, default='', null=True)),
                ('review_by', models.CharField(default='', max_length=254)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to='profiles.userprofile')),
            ],
        ),
    ]
