# Generated by Django 3.2 on 2022-01-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_volym'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discription',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
