# Generated by Django 3.2 on 2022-01-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='discription',
            new_name='description',
        ),
    ]
